[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@chainlink/=lib/chainlink-brownie-contracts/",
    "@core/=src/core/",
    "@interfaces/=src/interfaces/",
    "@mocks/=src/mocks/",
    "@test/=test/"
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
